esphome:
  name: pzem-017

esp32:
  variant: ESP32C3
  board: esp32-c3-devkitm-1

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password

api:
ota:
logger:

uart:
  baud_rate: 9600
  data_bits: 8
  stop_bits: 2
  parity: NONE
  tx_pin: GPIO10
  rx_pin: GPIO20

sensor:
  - platform: uptime
    name: "PZEM-017 uptime"
    update_interval: 30s
  - platform: wifi_signal
    name: "PZEM-017 WiFi Signal Sensor"
    update_interval: 30s

  - platform: pzemdc
    address: 30
    current:
      name: "PZEM-017 Current"
    voltage:
      name: "PZEM-017 Voltage"
    power:
      name: "PZEM-017 Power"
    energy:
      name: "PZEM-017 Energy"
    update_interval: 2s

switch:
  - platform: restart
    name: "PZEM-017 restart"

text_sensor:
  - platform: wifi_info
    ip_address:
      id: ip_address
      name: PZEM-017 IP Address
    ssid:
      name: PZEM-017 Connected SSID
